version: '3'
services:

  php:
    build:
      context: ./docker/apache
    ports:
      - 7090:80
    volumes: 
      - ./src:/var/www/html/
      - ./docker/apache/vhosts:/etc/apache2/sites-enabled

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --init-file="/tmp/database/inititialDatabase.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes: 
      - ./dbdata:/var/lib/mysql
      - ./docker/mysql/:/tmp/database
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    links: 
      - mysql:mysql
    ports:
      - 7091:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: test
      PMA_USER: root
      PMA_PASSWORD: test
